#!/usr/bin/env bash
#
# Run helper script
# Version: 1.0
#
# shellcheck disable=SC1090

set -euo pipefail
IFS=$'\n\t'

__root="$(dirname "$(realpath "$0")")"

source "${__root}"/../_lib/cli.sh

cmd_init() {
  docker swarm init --task-history-limit=2
}

cmd_defaults() {
  docker swarm update --task-history-limit=2
}

main "$@"