
version: '3.3'

services:
  elasticsearch:
    image: elasticsearch:7.5.1
    environment:
      node.name: 'SYD'
      discovery.type: 'single-node'
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    logging:
      driver: fluentd
      options:
        fluentd-address: host.docker.internal:24224
        fluentd-async-connect: 'true'
        fluentd-retry-wait: 1s
        fluentd-max-retries: 30
        tag: ${LOG_OPT_TAG_PREFIX}.efk.elasticsearch

  kibana:
    image: kibana:7.5.1
    ports:
      - 5601:5601
    logging:
      driver: fluentd
      options:
        fluentd-address: host.docker.internal:24224
        fluentd-async-connect: 'true'
        fluentd-retry-wait: 1s
        fluentd-max-retries: 30
        tag: ${LOG_OPT_TAG_PREFIX}.efk.kibana

  fluentd:
    image: plavchub/fluentd:v1.8-1-elasticsearch
    environment:
      ELASTICSEARCH_HOST: elasticsearch
    configs:
      - source: fluentd_conf
        target: /fluentd/etc/fluent.conf
    ports:
      - 24224:24224
      - 24224:24224/udp
    logging:
      driver: json-file
      options:
        max-size: 1G
        max-file: 2

volumes:
  elasticsearch-data:

configs:
  fluentd_conf:
    file: ./config/fluentd.conf