
version: '3.4'

x-logging-options:
  &fluentd-logging-options
  fluentd-address: host.docker.internal:24224
  fluentd-async-connect: 'true'
  fluentd-retry-wait: 1s
  fluentd-max-retries: 30

services:

  elasticsearch:
    image: elasticsearch:${IMAGE_TAG_ELASTICSEARCH?}
    environment:
      node.name: 'SYD'
      discovery.type: 'single-node'
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200
      - 9300
    logging:
      driver: fluentd
      options:
        << : *fluentd-logging-options
        tag: ${LOG_OPT_TAG_PREFIX}.efk.elasticsearch

  kibana:
    image: kibana:${IMAGE_TAG_KIBANA?}
    ports:
      - 5601
    logging:
      driver: fluentd
      options:
        << : *fluentd-logging-options
        tag: ${LOG_OPT_TAG_PREFIX}.efk.elasticsearch

  fluentd:
    image: ${IMAGE_FLUENTD?}
    environment:
      ELASTICSEARCH_HOST: elasticsearch
    configs:
      - source: fluentd_conf
        target: /fluentd/etc/fluent.conf
    ports:
      - 24224:24224
      - 24224:24224/udp
    logging:
      driver: json-file
      options:
        max-size: 1G
        max-file: 2

volumes:
  elasticsearch-data:

configs:
  fluentd_conf:
    file: ./config/fluentd.conf