
version: '3.4'

x-configs:
  &rmq-config
  - source: rmq-enabled_plugins
    target: /etc/rabbitmq/enabled_plugins
  - source: rmq-rabbitmq_conf
    target: /etc/rabbitmq/rabbitmq.conf

x-deploys:
  &rmq-deploy
  replicas: 1
  restart_policy:
    condition: on-failure

services:

  rmq-01:
    image: rabbitmq:${IMAGE_TAG_RABBITMQ?}
    environment: 
      RABBITMQ_ERLANG_COOKIE: test-secret-cookie
      RABBITMQ_NODENAME: rabbit@rmq-01
    volumes:
      - rmq-01:/var/lib/rabbitmq
    configs: *rmq-config
    deploy: *rmq-deploy

  rmq-02:
    image: rabbitmq:${IMAGE_TAG_RABBITMQ?}
    environment: 
      RABBITMQ_ERLANG_COOKIE: test-secret-cookie
      RABBITMQ_NODENAME: rabbit@rmq-02
    volumes:
      - rmq-02:/var/lib/rabbitmq
    configs: *rmq-config
    deploy: *rmq-deploy

  rmq-03:
    image: rabbitmq:${IMAGE_TAG_RABBITMQ?}
    environment: 
      RABBITMQ_ERLANG_COOKIE: test-secret-cookie
      RABBITMQ_NODENAME: rabbit@rmq-03
    volumes:
      - rmq-03:/var/lib/rabbitmq
    configs: *rmq-config
    deploy: *rmq-deploy

  haproxy:
    image: haproxy:${IMAGE_TAG_HAPROXY?}
    configs:
    - source: haproxy_cfg
      target: /usr/local/etc/haproxy/haproxy.cfg
    environment:
      MODE: tcp
    ports:
      - 80
      - 5672
      - 15672

volumes:
  rmq-01:
  rmq-02:
  rmq-03:

configs:
  rmq-enabled_plugins:
    file: ./config/rabbitmq_plugins.txt
  rmq-rabbitmq_conf:
    file: ./config/rabbitmq.conf
  haproxy_cfg:
    file: ./config/haproxy.cfg