
version: '3.4'

services:

  haproxy:
    image: haproxy:${IMAGE_TAG_HAPROXY?}
    configs:
    - source: haproxy_cfg
      target: /usr/local/etc/haproxy/haproxy.cfg
    environment:
      MODE: tcp
    ports:
      - 80
      - 8080

  example:
    image: nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M

configs:
  haproxy_cfg:
    file: ./config/haproxy.cfg