
version: '3.4'

services:

  nginx:
    image: nginx:${IMAGE_TAG_NGINX?}
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - 80
    configs:
      - source: nginx-config-template
        target: /etc/nginx/conf.d/default.template
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M

configs:
  nginx-config-template:
    file: ./config/default.template
