
version: '3.4'

x-deploys:
  &rmq-deploy
  replicas: 1
  restart_policy:
    condition: on-failure
    delay: 10s
    max_attempts: 3
    window: 120s

services:

  mysql:
    image: mysql:${IMAGE_TAG_MYSQL?}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root
    volumes:
      - mysql-data:/var/lib/mysql
    configs:
      - source: mysql-init-sql
        target: /docker-entrypoint-initdb.d/init.sql
    secrets:
      - source: mysql-passwd
        target: /run/secrets/mysql-root
    deploy: *rmq-deploy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${IMAGE_TAG_PHPMYADMIN?}
    ports:
      - 80
    environment:
      PMA_HOST: mysql
    deploy: *rmq-deploy

  adminer:
    image: adminer:${IMAGE_TAG_ADMINER?}
    ports:
      - 8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    deploy: *rmq-deploy

volumes:
  mysql-data:

configs:
  mysql-init-sql:
    file: ./config/init.sql

secrets:
  mysql-passwd:
    file: ./config/passwd.txt