#!/usr/bin/env bash
#
# Run helper script
# Version: 1.0
#
# shellcheck disable=SC1090

set -euo pipefail
IFS=$'\n\t'

__root="$(dirname "$(realpath "$0")")"

readonly DOCKER_STACK_NAME="mysql"

source "${__root}"/../_lib/cli.sh
source "${__root}"/../_lib/stack.sh

main "$@"