
version: '3.4'

services:

  wireshark:
    image: manell/wireshark
    ports:
      - 80
      - 25
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first


        docker run -ti --net=host --privileged -v $HOME:/root:ro -e XAUTHORITY=/root/.Xauthority -e DISPLAY=$DISPLAY manell/wireshark