
version: '3.3'

services:

  mongo:
    image: mongo:4.2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  express:
    image: mongo-express
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  mongo-data:
  mongo-config:
